#!/bin/bash

FILES_TO_COMMIT=$(git diff --cached --name-only --diff-filter=ACM)
echo $FILES_TO_COMMIT is going to commit.

for file in $FILES_TO_COMMIT; do
  TEMP_FILE=$(mktemp)
  git show ":$file" > $TEMP_FILE
  if ! diff $file $TEMP_FILE ; then
    echo $file is changed after add, please git add it.
    exit 1
  fi
done

cd build
if [ $? != 0 ]; then
  echo Missing build directory!
  exit 1
fi


if ! make clangformat_check &> /dev/null ; then
  echo Please clang-format your code
  exit 1
fi

exit 0
